package maestro.cli.command

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import maestro.Filters
import maestro.Maestro
import maestro.SwipeDirection
import maestro.cli.App
import maestro.cli.DisableAnsiMixin
import maestro.cli.ShowHelpMixin
import maestro.cli.report.TestDebugReporter
import maestro.cli.session.MaestroSessionManager
import okio.buffer
import okio.sink
import org.fusesource.jansi.Ansi.ansi
import picocli.CommandLine
import java.io.File

@CommandLine.Command(
    name = "interact",
    description = [
        "Start an interactive REPL session for controlling a connected device"
    ]
)
class InteractCommand : Runnable {

    @CommandLine.Mixin
    var disableANSIMixin: DisableAnsiMixin? = null

    @CommandLine.Mixin
    var showHelpMixin: ShowHelpMixin? = null

    @CommandLine.ParentCommand
    private val parent: App? = null

    @CommandLine.Option(
        names = ["--reinstall-driver"],
        description = ["Reinstalls driver before running. On iOS, reinstalls xctestrunner driver. On Android, reinstalls both driver and server apps."],
        negatable = true,
        defaultValue = "true",
        fallbackValue = "true"
    )
    private var reinstallDriver: Boolean = true

    @CommandLine.Option(
        names = ["--apple-team-id"],
        description = ["The Team ID is a unique 10-character string generated by Apple that is assigned to your team's apple account."],
        hidden = true
    )
    private var appleTeamId: String? = null

    @CommandLine.Option(
        names = ["--device-index"],
        description = ["The index of the device to run on"],
        hidden = true
    )
    private var deviceIndex: Int? = null

    override fun run() {
        TestDebugReporter.install(
            debugOutputPathAsString = null,
            flattenDebugOutput = false,
            printToConsole = parent?.verbose == true,
        )

        MaestroSessionManager.newSession(
            host = parent?.host,
            port = parent?.port,
            driverHostPort = null,
            teamId = appleTeamId,
            deviceId = parent?.deviceId,
            platform = parent?.platform,
            reinstallDriver = reinstallDriver,
            deviceIndex = deviceIndex
        ) { session ->
            runRepl(session.maestro)
        }
    }

    private fun runRepl(maestro: Maestro) {
        printWelcome()

        while (true) {
            print(ansi().fgBrightCyan().a("maestro> ").reset().toString())
            val input = readLine()

            if (input == null) {
                println("Goodbye!")
                return
            }

            val trimmedInput = input.trim()
            if (trimmedInput.isEmpty()) {
                continue
            }

            when (val command = parseCommand(trimmedInput)) {
                is ParsedCommand.Quit -> {
                    println("Goodbye!")
                    return
                }
                is ParsedCommand.Help -> printHelp()
                is ParsedCommand.Unknown -> {
                    printError("Unknown command: ${command.input}")
                    println("Type 'help' for available commands.")
                }
                is ParsedCommand.Error -> {
                    printError(command.message)
                }
                else -> executeCommand(maestro, command)
            }
        }
    }

    private fun printWelcome() {
        println(
            """

            Welcome to Maestro Interactive Mode!

            Control your device with simple commands.
            Type 'help' for available commands, 'quit' to exit.

            """.trimIndent()
        )
    }

    private fun printHelp() {
        println(
            """

            Available commands:

              tap <text>        Tap on element containing text (e.g., tap Login)
              press <text>      Same as tap
              type <text>       Input text (e.g., type hello@email.com)
              input <text>      Same as type
              swipe <dir>       Swipe in direction: up, down, left, right
              back              Press back button
              scroll            Scroll down
              erase <count>     Erase characters (e.g., erase 10)
              launch <app>      Launch app by package/bundle ID
              screenshot [path] Take screenshot (default: screenshot.png)
              hierarchy         Print view hierarchy as JSON
              help              Show this help message
              quit / exit       Exit interactive mode

            """.trimIndent()
        )
    }

    private fun parseCommand(input: String): ParsedCommand {
        val parts = input.split(Regex("\\s+"), limit = 2)
        val command = parts[0].lowercase()
        val argument = parts.getOrNull(1)?.trim()

        return when (command) {
            "quit", "exit" -> ParsedCommand.Quit
            "help" -> ParsedCommand.Help
            "tap", "press" -> {
                if (argument.isNullOrBlank()) {
                    ParsedCommand.Error("$command requires text argument")
                } else {
                    ParsedCommand.Tap(argument)
                }
            }
            "type", "input" -> {
                if (argument.isNullOrBlank()) {
                    ParsedCommand.Error("$command requires text argument")
                } else {
                    ParsedCommand.Type(argument)
                }
            }
            "swipe" -> {
                when (argument?.lowercase()) {
                    "up" -> ParsedCommand.Swipe(SwipeDirection.UP)
                    "down" -> ParsedCommand.Swipe(SwipeDirection.DOWN)
                    "left" -> ParsedCommand.Swipe(SwipeDirection.LEFT)
                    "right" -> ParsedCommand.Swipe(SwipeDirection.RIGHT)
                    null, "" -> ParsedCommand.Error("swipe requires direction: up, down, left, right")
                    else -> ParsedCommand.Error("Unknown swipe direction: $argument")
                }
            }
            "back" -> ParsedCommand.Back
            "scroll" -> ParsedCommand.Scroll
            "erase" -> {
                val count = argument?.toIntOrNull()
                if (count == null || count <= 0) {
                    ParsedCommand.Error("erase requires a positive number (e.g., erase 10)")
                } else {
                    ParsedCommand.Erase(count)
                }
            }
            "launch" -> {
                if (argument.isNullOrBlank()) {
                    ParsedCommand.Error("launch requires app package/bundle ID")
                } else {
                    ParsedCommand.Launch(argument)
                }
            }
            "screenshot" -> ParsedCommand.Screenshot(argument ?: "screenshot.png")
            "hierarchy" -> ParsedCommand.Hierarchy
            else -> ParsedCommand.Unknown(input)
        }
    }

    private fun executeCommand(maestro: Maestro, command: ParsedCommand) {
        try {
            when (command) {
                is ParsedCommand.Tap -> executeTap(maestro, command.text)
                is ParsedCommand.Type -> executeType(maestro, command.text)
                is ParsedCommand.Swipe -> executeSwipe(maestro, command.direction)
                is ParsedCommand.Back -> executeBack(maestro)
                is ParsedCommand.Scroll -> executeScroll(maestro)
                is ParsedCommand.Erase -> executeErase(maestro, command.count)
                is ParsedCommand.Launch -> executeLaunch(maestro, command.appId)
                is ParsedCommand.Screenshot -> executeScreenshot(maestro, command.path)
                is ParsedCommand.Hierarchy -> executeHierarchy(maestro)
                is ParsedCommand.Help, is ParsedCommand.Quit, is ParsedCommand.Unknown, is ParsedCommand.Error -> {
                    // Handled in runRepl
                }
            }
        } catch (e: Exception) {
            printError("Error: ${e.message}")
        }
    }

    private fun executeTap(maestro: Maestro, text: String) {
        val regex = ".*${Regex.escape(text)}.*".toRegex(RegexOption.IGNORE_CASE)
        val filter = Filters.textMatches(regex)

        val result = maestro.findElementWithTimeout(10000L, filter)
        if (result == null) {
            printError("Element not found: $text")
            return
        }

        maestro.tap(result.element, result.hierarchy)
        printSuccess("Tapped on '$text'")
    }

    private fun executeType(maestro: Maestro, text: String) {
        maestro.inputText(text)
        printSuccess("Typed '$text'")
    }

    private fun executeSwipe(maestro: Maestro, direction: SwipeDirection) {
        maestro.swipe(swipeDirection = direction, duration = 400)
        printSuccess("Swiped ${direction.name.lowercase()}")
    }

    private fun executeBack(maestro: Maestro) {
        maestro.backPress()
        printSuccess("Pressed back")
    }

    private fun executeScroll(maestro: Maestro) {
        maestro.scrollVertical()
        printSuccess("Scrolled")
    }

    private fun executeErase(maestro: Maestro, count: Int) {
        maestro.eraseText(count)
        printSuccess("Erased $count character${if (count > 1) "s" else ""}")
    }

    private fun executeLaunch(maestro: Maestro, appId: String) {
        maestro.launchApp(appId)
        printSuccess("Launched $appId")
    }

    private fun executeScreenshot(maestro: Maestro, path: String) {
        val file = File(path)
        file.sink().buffer().use { sink ->
            maestro.takeScreenshot(sink, compressed = false)
        }
        printSuccess("Screenshot saved to ${file.absolutePath}")
    }

    private fun executeHierarchy(maestro: Maestro) {
        val tree = maestro.viewHierarchy().root
        val hierarchy = jacksonObjectMapper()
            .setSerializationInclusion(JsonInclude.Include.NON_NULL)
            .writerWithDefaultPrettyPrinter()
            .writeValueAsString(tree)
        println(hierarchy)
    }

    private fun printSuccess(message: String) {
        println(ansi().fgBrightGreen().a("✓ ").reset().a(message).toString())
    }

    private fun printError(message: String) {
        println(ansi().fgBrightRed().a("✗ ").reset().a(message).toString())
    }

    private sealed class ParsedCommand {
        data class Tap(val text: String) : ParsedCommand()
        data class Type(val text: String) : ParsedCommand()
        data class Swipe(val direction: SwipeDirection) : ParsedCommand()
        object Back : ParsedCommand()
        object Scroll : ParsedCommand()
        data class Erase(val count: Int) : ParsedCommand()
        data class Launch(val appId: String) : ParsedCommand()
        data class Screenshot(val path: String) : ParsedCommand()
        object Hierarchy : ParsedCommand()
        object Help : ParsedCommand()
        object Quit : ParsedCommand()
        data class Unknown(val input: String) : ParsedCommand()
        data class Error(val message: String) : ParsedCommand()
    }
}
