package maestro.cli.command

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import maestro.Filters
import maestro.Maestro
import maestro.SwipeDirection
import maestro.cli.App
import maestro.cli.DisableAnsiMixin
import maestro.cli.ShowHelpMixin
import maestro.cli.report.TestDebugReporter
import maestro.cli.session.MaestroSessionManager
import okio.buffer
import okio.sink
import org.fusesource.jansi.Ansi.ansi
import org.jline.reader.EndOfFileException
import org.jline.reader.LineReaderBuilder
import org.jline.reader.UserInterruptException
import org.jline.terminal.TerminalBuilder
import picocli.CommandLine
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import java.io.File
import java.io.PrintWriter
import java.util.concurrent.ConcurrentLinkedQueue

@CommandLine.Command(
    name = "interact",
    description = [
        "Start an interactive REPL session for controlling a connected device"
    ]
)
class InteractCommand : Runnable {

    @CommandLine.Mixin
    var disableANSIMixin: DisableAnsiMixin? = null

    @CommandLine.Mixin
    var showHelpMixin: ShowHelpMixin? = null

    @CommandLine.ParentCommand
    private val parent: App? = null

    @CommandLine.Option(
        names = ["--reinstall-driver"],
        description = ["Reinstalls driver before running. On iOS, reinstalls xctestrunner driver. On Android, reinstalls both driver and server apps."],
        negatable = true,
        defaultValue = "true",
        fallbackValue = "true"
    )
    private var reinstallDriver: Boolean = true

    @CommandLine.Option(
        names = ["--apple-team-id"],
        description = ["The Team ID is a unique 10-character string generated by Apple that is assigned to your team's apple account."],
        hidden = true
    )
    private var appleTeamId: String? = null

    @CommandLine.Option(
        names = ["--device-index"],
        description = ["The index of the device to run on"],
        hidden = true
    )
    private var deviceIndex: Int? = null

    override fun run() {
        TestDebugReporter.install(
            debugOutputPathAsString = null,
            flattenDebugOutput = false,
            printToConsole = parent?.verbose == true,
        )

        MaestroSessionManager.newSession(
            host = parent?.host,
            port = parent?.port,
            driverHostPort = null,
            teamId = appleTeamId,
            deviceId = parent?.deviceId,
            platform = parent?.platform,
            reinstallDriver = reinstallDriver,
            deviceIndex = deviceIndex
        ) { session ->
            runRepl(session.maestro)
        }
    }

    private fun runRepl(maestro: Maestro) {
        printWelcome()

        val terminal = TerminalBuilder.builder().jansi(true).build()
        try {
            val lineReader = LineReaderBuilder.builder().terminal(terminal).build()
            val emitResult: (String) -> Unit = { line -> lineReader.printAbove(line) }
            val prompt = interactPromptString()

            runBlocking {
                val commandQueue = Channel<ParsedCommand>(Channel.UNLIMITED)
                val pendingDescriptions = ConcurrentLinkedQueue<String>()
                val out = terminal.writer()

                val readerJob = launch(Dispatchers.IO) {
                    try {
                        while (true) {
                            val trimmedInput = try {
                                lineReader.readLine(prompt).trim()
                            } catch (_: UserInterruptException) {
                                continue
                            } catch (_: EndOfFileException) {
                                out.println()
                                out.println("Goodbye!")
                                out.flush()
                                commandQueue.close()
                                return@launch
                            }

                            if (trimmedInput.isEmpty()) {
                                continue
                            }

                            when (val command = parseCommand(trimmedInput)) {
                                is ParsedCommand.Quit -> {
                                    out.println("Goodbye!")
                                    out.flush()
                                    commandQueue.close()
                                    return@launch
                                }
                                is ParsedCommand.Help -> printHelp(out)
                                is ParsedCommand.Unknown -> {
                                    out.println(readerErrorLine("Unknown command: ${command.input}"))
                                    out.println("Type 'help' for available commands.")
                                    out.flush()
                                }
                                is ParsedCommand.Error -> {
                                    out.println(readerErrorLine(command.message))
                                    out.flush()
                                }
                                else -> {
                                    val description = describeQueuedCommand(command)
                                    pendingDescriptions.offer(description)
                                    lineReader.printAbove(queuedNoticeLine(description))
                                    commandQueue.send(command)
                                }
                            }
                        }
                    } catch (e: CancellationException) {
                        throw e
                    } catch (e: Exception) {
                        lineReader.printAbove(readerErrorLine("REPL error: ${e.message}"))
                        commandQueue.close()
                    }
                }

                val workerJob = launch(Dispatchers.IO) {
                    try {
                        for (command in commandQueue) {
                            executeCommand(maestro, command, emitResult)
                            pendingDescriptions.poll()
                        }
                    } catch (e: CancellationException) {
                        throw e
                    }
                }

                readerJob.join()
                workerJob.join()
            }
        } finally {
            terminal.close()
        }
    }

    private fun interactPromptString(): String =
        if (DisableAnsiMixin.ansiEnabled) {
            ansi().fgBrightCyan().a("maestro> ").reset().toString()
        } else {
            "maestro> "
        }

    private fun readerErrorLine(message: String): String =
        ansi().fgBrightRed().a("✗ ").reset().a(message).toString()

    private fun queuedNoticeLine(description: String): String =
        if (DisableAnsiMixin.ansiEnabled) {
            ansi().fgBrightYellow().a("Queued: ").reset().a(description).toString()
        } else {
            "Queued: $description"
        }

    private fun describeQueuedCommand(command: ParsedCommand): String =
        when (command) {
            is ParsedCommand.Tap -> "tap ${command.text}"
            is ParsedCommand.Type -> "type ${command.text}"
            is ParsedCommand.Swipe -> "swipe ${command.direction.name.lowercase()}"
            is ParsedCommand.Back -> "back"
            is ParsedCommand.Scroll -> "scroll"
            is ParsedCommand.Erase -> "erase ${command.count}"
            is ParsedCommand.Launch -> "launch ${command.appId}"
            is ParsedCommand.Screenshot -> "screenshot ${command.path}"
            is ParsedCommand.Hierarchy -> "hierarchy"
            is ParsedCommand.Help,
            is ParsedCommand.Quit,
            is ParsedCommand.Unknown,
            is ParsedCommand.Error ->
                error("command is not queued for execution: $command")
        }

    private fun printWelcome() {
        println(
            """

            Welcome to Maestro Interactive Mode!

            Control your device with simple commands.
            Type 'help' for available commands, 'quit' to exit.

            """.trimIndent()
        )
    }

    private fun printHelp(out: PrintWriter) {
        out.print(
            """

            Available commands:

              tap <text>        Tap on element containing text (e.g., tap Login)
              press <text>      Same as tap
              type <text>       Input text (e.g., type hello@email.com)
              input <text>      Same as type
              swipe <dir>       Swipe in direction: up, down, left, right
              back              Press back button
              scroll            Scroll down
              erase <count>     Erase characters (e.g., erase 10)
              launch <app>      Launch app by package/bundle ID
              screenshot [path] Take screenshot (default: screenshot.png)
              hierarchy         Print view hierarchy as JSON
              help              Show this help message
              quit / exit       Exit interactive mode

            """.trimIndent()
        )
        out.flush()
    }

    private fun parseCommand(input: String): ParsedCommand {
        val parts = input.split(Regex("\\s+"), limit = 2)
        val command = parts[0].lowercase()
        val argument = parts.getOrNull(1)?.trim()

        return when (command) {
            "quit", "exit" -> ParsedCommand.Quit
            "help" -> ParsedCommand.Help
            "tap", "press" -> {
                if (argument.isNullOrBlank()) {
                    ParsedCommand.Error("$command requires text argument")
                } else {
                    ParsedCommand.Tap(argument)
                }
            }
            "type", "input" -> {
                if (argument.isNullOrBlank()) {
                    ParsedCommand.Error("$command requires text argument")
                } else {
                    ParsedCommand.Type(argument)
                }
            }
            "swipe" -> {
                when (argument?.lowercase()) {
                    "up" -> ParsedCommand.Swipe(SwipeDirection.UP)
                    "down" -> ParsedCommand.Swipe(SwipeDirection.DOWN)
                    "left" -> ParsedCommand.Swipe(SwipeDirection.LEFT)
                    "right" -> ParsedCommand.Swipe(SwipeDirection.RIGHT)
                    null, "" -> ParsedCommand.Error("swipe requires direction: up, down, left, right")
                    else -> ParsedCommand.Error("Unknown swipe direction: $argument")
                }
            }
            "back" -> ParsedCommand.Back
            "scroll" -> ParsedCommand.Scroll
            "erase" -> {
                val count = argument?.toIntOrNull()
                if (count == null || count <= 0) {
                    ParsedCommand.Error("erase requires a positive number (e.g., erase 10)")
                } else {
                    ParsedCommand.Erase(count)
                }
            }
            "launch" -> {
                if (argument.isNullOrBlank()) {
                    ParsedCommand.Error("launch requires app package/bundle ID")
                } else {
                    ParsedCommand.Launch(argument)
                }
            }
            "screenshot" -> ParsedCommand.Screenshot(argument ?: "screenshot.png")
            "hierarchy" -> ParsedCommand.Hierarchy
            else -> ParsedCommand.Unknown(input)
        }
    }

    private fun executeCommand(maestro: Maestro, command: ParsedCommand, emit: (String) -> Unit) {
        try {
            when (command) {
                is ParsedCommand.Tap -> executeTap(maestro, command.text, emit)
                is ParsedCommand.Type -> executeType(maestro, command.text, emit)
                is ParsedCommand.Swipe -> executeSwipe(maestro, command.direction, emit)
                is ParsedCommand.Back -> executeBack(maestro, emit)
                is ParsedCommand.Scroll -> executeScroll(maestro, emit)
                is ParsedCommand.Erase -> executeErase(maestro, command.count, emit)
                is ParsedCommand.Launch -> executeLaunch(maestro, command.appId, emit)
                is ParsedCommand.Screenshot -> executeScreenshot(maestro, command.path, emit)
                is ParsedCommand.Hierarchy -> executeHierarchy(maestro, emit)
                is ParsedCommand.Help, is ParsedCommand.Quit, is ParsedCommand.Unknown, is ParsedCommand.Error -> {
                    // Handled in runRepl
                }
            }
        } catch (e: Exception) {
            emitResultError("Error: ${e.message}", emit)
        }
    }

    private fun executeTap(maestro: Maestro, text: String, emit: (String) -> Unit) {
        val regex = ".*${Regex.escape(text)}.*".toRegex(RegexOption.IGNORE_CASE)
        val filter = Filters.textMatches(regex)

        val result = maestro.findElementWithTimeout(10000L, filter)
        if (result == null) {
            emitResultError("Element not found: $text", emit)
            return
        }

        maestro.tap(result.element, result.hierarchy)
        emitResultSuccess("Tapped on '$text'", emit)
    }

    private fun executeType(maestro: Maestro, text: String, emit: (String) -> Unit) {
        maestro.inputText(text)
        emitResultSuccess("Typed '$text'", emit)
    }

    private fun executeSwipe(maestro: Maestro, direction: SwipeDirection, emit: (String) -> Unit) {
        maestro.swipe(swipeDirection = direction, duration = 400)
        emitResultSuccess("Swiped ${direction.name.lowercase()}", emit)
    }

    private fun executeBack(maestro: Maestro, emit: (String) -> Unit) {
        maestro.backPress()
        emitResultSuccess("Pressed back", emit)
    }

    private fun executeScroll(maestro: Maestro, emit: (String) -> Unit) {
        maestro.scrollVertical()
        emitResultSuccess("Scrolled", emit)
    }

    private fun executeErase(maestro: Maestro, count: Int, emit: (String) -> Unit) {
        maestro.eraseText(count)
        emitResultSuccess("Erased $count character${if (count > 1) "s" else ""}", emit)
    }

    private fun executeLaunch(maestro: Maestro, appId: String, emit: (String) -> Unit) {
        maestro.launchApp(appId)
        emitResultSuccess("Launched $appId", emit)
    }

    private fun executeScreenshot(maestro: Maestro, path: String, emit: (String) -> Unit) {
        val file = File(path)
        file.sink().buffer().use { sink ->
            maestro.takeScreenshot(sink, compressed = false)
        }
        emitResultSuccess("Screenshot saved to ${file.absolutePath}", emit)
    }

    private fun executeHierarchy(maestro: Maestro, emit: (String) -> Unit) {
        val tree = maestro.viewHierarchy().root
        val hierarchy = jacksonObjectMapper()
            .setSerializationInclusion(JsonInclude.Include.NON_NULL)
            .writerWithDefaultPrettyPrinter()
            .writeValueAsString(tree)
        emit(hierarchy)
    }

    private fun emitResultSuccess(message: String, emit: (String) -> Unit) {
        emit(ansi().fgBrightGreen().a("✓ ").reset().a(message).toString())
    }

    private fun emitResultError(message: String, emit: (String) -> Unit) {
        emit(ansi().fgBrightRed().a("✗ ").reset().a(message).toString())
    }

    private sealed class ParsedCommand {
        data class Tap(val text: String) : ParsedCommand()
        data class Type(val text: String) : ParsedCommand()
        data class Swipe(val direction: SwipeDirection) : ParsedCommand()
        object Back : ParsedCommand()
        object Scroll : ParsedCommand()
        data class Erase(val count: Int) : ParsedCommand()
        data class Launch(val appId: String) : ParsedCommand()
        data class Screenshot(val path: String) : ParsedCommand()
        object Hierarchy : ParsedCommand()
        object Help : ParsedCommand()
        object Quit : ParsedCommand()
        data class Unknown(val input: String) : ParsedCommand()
        data class Error(val message: String) : ParsedCommand()
    }
}
